archives:
  - replacements:
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
builds:
  - ldflags:
    - -H windowsgui
    goos:
      - windows
  - goos:
      - darwin
      - linux
      - freebsd