archives:
  - replacements:
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
builds:
  - id: "windows"
    goos:
      - windows
    ldflags:
    - -s -w -H windowsgui
  - id: "others"
    goos:
      - darwin
      - linux
      - freebsd
    ldflags:
    - -s -w